language: c
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq git
    - sudo pip install --upgrade pip
    - echo Current branch ${TRAVIS_BRANCH}
after_success:
    - mkdir -p build/usr/share/asm2k2/
    - cd build && tar -c * > ../asm2k2.tar && cd ..
    - gzip asm2k2.tar
    - mv asm2k2.tar.gz asm2k2.tgz
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then VERSION=`cat VERSION`; else VERSION=alpha; fi'
    - echo $VERSION
    - curl -X POST --data-binary '@asm2k2.tgz' "https://cdn.oric.org/publish.php?hash=$hash&path=/home/oricoujr/www/ftp/orix/dists/$VERSION/tgz/6502/asm2k2.tgz"    

